package com.fire.bookbuddy.Docs
//THIS FILE IS SPECIFICALLY MADE FOR DEV TO UNDERSTAND FULL WORKING OF PROJECT, ITS FLOW AND ARCHITECTURE. CLASSES ARE DOCUMENTED IN THE PROJECT.
/**
 *
 *
 *
 *
 *
 */